In [4]:
pip install numpy


In [7]:
import numpy as np

arr=np.array([1,2,3])

arr

array([1, 2, 3])

In [13]:
import numpy as np

arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr.shape

(3,)

In [15]:
arr_2d.shape

(3, 3)

In [16]:
#Numpy로 연산하기

In [21]:
x=np.array([1,2,3])
c=5

print('더하기 : {}'.format(x+c))
print('빼기 : {}'.format(x-c))
print('곱하기 : {}'.format(x*c))
print('나누기 : {}'.format(x/c))

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


In [23]:
y=np.array([1,3,5])
z=np.array([2,9,20])

print('더하기 : {}'.format(y+z))
print('빼기 : {}'.format(y-z))
print('곱하기 : {}'.format(y*z))
print('나누기 : {}'.format(y/z))

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


In [25]:
w=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

w[0,0]

1

In [26]:
w[2,3]

12

In [27]:
#7을 가져오려면
w[1,2]

7

In [28]:
w=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

#w의 2,3,6,7을 가져오고 싶을 때
# 2,3 --> 행 : 인덱스 0~1 --> [0:2]
#6,7  -->열 : 인덱스 1~2  -->[1:3]
w[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [30]:
w[0:2, 0:4]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
w[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
w[0:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
w[0:3, 2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [34]:
w[:,2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [36]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
x=np.array([0,1,0])

x=x[:,None]    #x를 전치
print(a+x)

[[1 2 3]
 [5 6 7]
 [7 8 9]]


In [37]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
x=np.array([0,1,0])

print(a+x)

[[1 3 3]
 [4 6 6]
 [7 9 9]]


In [38]:
y=np.array([0,1,-1])

print(a*y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


In [39]:
t=np.array([1,2,3])  #열벡터로 바꿔줘야 함!
t= t[:,None] #Traaspose

u=np.array([2,0,-2])

print(t+u)

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


In [41]:
np.zeros(3)

array([0., 0., 0.])

In [42]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.ones(2)

array([1., 1.])

In [44]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.diag((2,4))

array([[2, 0],
       [0, 4]])

In [46]:
np.diag((1,3,5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [47]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [48]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [50]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
mat_1=np.array([[1,4],[2,3]])
mat_2=np.array([[7,9],[0,6]])

mat_1.dot(mat_2)

array([[ 7, 33],
       [14, 36]])

In [52]:
mat_1@mat_2

array([[ 7, 33],
       [14, 36]])

In [53]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr.trace()

15

In [56]:
np.eye(2,dtype=int).trace()

2

In [57]:
arr_2=np.array([[2,3],[1,6]])

arr_2

array([[2, 3],
       [1, 6]])

In [58]:
np.linalg.det(arr_2)

9.000000000000002

In [59]:
arr_3=np.array([[1,4,7],[2,5,8],[3,6,9]])

arr_3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [60]:
np.linalg.det(arr_3)

0.0

In [61]:
mat=np.array([[1,4],[2,3]])

mat

array([[1, 4],
       [2, 3]])

In [62]:
mat_inv=np.linalg.inv(mat)

mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [63]:
mat @ mat_inv

array([[1., 0.],
       [0., 1.]])

In [64]:
mat=np.array([[2,0,-2],[1,1,-2],[0,0,1]])

mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [65]:
np.linalg.eig(mat)

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

In [66]:
eig_val, eig_vec = np.linalg.eig(mat)
eig_val

array([1., 2., 1.])

In [67]:
eig_vec

array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]])

In [68]:
mat @ eig_vec[:,0]

array([0., 1., 0.])

In [69]:
eig_val[0] * eig_vec[:,0] #벡터와 스칼라 사이의 곱이기 때문에 @로 곱하지 않는다.

array([0., 1., 0.])